name: Remove NBA Contracts

on:
  workflow_dispatch:

jobs:
  remove_contracts:
    name: Remove NBA Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Run removal script
        run: python -c "from scraper import remove_contracts; remove_contracts()"

      - name: Commit and push removal
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nba_contracts.csv
          git commit -m "Removed NBA contracts" || echo "No changes to commit"
          git push
